"""PURPOSE: generate LaTeX macros for every number in the paper.
INPUTS: results/results.json, results/multiseed_stats.json, results/multiseed_per_seed.csv and the
        single-seed daily CSVs.
OUTPUTS: paper/numbers.tex (macros plus the \\ByYearRows table body) for overfitting_test.tex.
"""

import json
from collections import Counter
from typing import Any

import numpy as np
import pandas as pd

from .config import ROOT


def command(name: str, value: Any) -> str:
    return f"\\newcommand{{\\{name}}}{{{value}}}"


def number(value: float, digits: int = 2) -> str:
    return f"{value:.{digits}f}"


def signed(value: float, digits: int = 2) -> str:
    text = f"{value:+.{digits}f}"
    if float(text) == 0.0:
        text = f"{0:.{digits}f}"
    return text.replace("-", "$-$")


def plain(value: float, digits: int = 2) -> str:
    return f"{value:.{digits}f}".replace("-", "$-$")


def percent(value: float, digits: int = 1) -> str:
    return f"{100 * value:.{digits}f}\\%".replace("-", "$-$")


def main() -> None:
    results = json.loads((ROOT / "results" / "results.json").read_text())
    stats = json.loads((ROOT / "results" / "multiseed_stats.json").read_text())
    per_seed = pd.read_csv(ROOT / "results" / "multiseed_per_seed.csv")
    config = results["config"]
    across, boot = stats["across_seeds"], stats["market_bootstrap"]
    means, extremes, sample = stats["per_seed_means"], stats["per_seed_extremes"], stats["sample"]
    lines = ["% Generated by make_latex_numbers.py from results/*.json; do not edit."]

    def add(name: str, value: Any) -> None:
        lines.append(command(name, value))

    for name, value in {
        "OOSStart": sample["oos_start"], "OOSEnd": sample["oos_end"],
        "OOSObs": f"{sample['oos_observations']:,}".replace(",", "{,}"),
        "NSeeds": across["n_seeds"], "SingleSeed": config["random_seed"],
        "HoldoutDays": config["holdout_days"], "BlockLen": config["block_len"],
        "RandomBlocks": config["random_blocks"], "GapDays": config["gap_days"],
        "MinSegment": config["min_segment"], "VolWindow": config["volatility_window"],
        "MomWindow": config["momentum_window"], "ValidationDays": config["validation_days"],
        "OrderFrequency": config["order_selection_frequency"],
        "RefitFrequency": config["refit_frequency"], "ComplexityPenalty": number(config["complexity_penalty"], 3),
        "CostBps": number(config["realized_cost_bps"], 0), "HMMIterations": config["hmm_iterations"],
        "CandidateStates": "2,\\ldots,6", "FeatureDim": 3 * len(config["tickers"]),
    }.items():
        add(name, value)

    # single seed (results.json) with a paired t-statistic on the daily gross-return difference
    for key, prefix in (("baseline_last126", "One Base"), ("blocked_cv", "One Blk")):
        method = results["methods"][key]
        tag = prefix.replace(" ", "")
        add(f"{tag}Sharpe", number(method["gross"]["sharpe"]))
        add(f"{tag}MaxDD", percent(method["gross"]["max_drawdown"]))
        add(f"{tag}Return", percent(method["gross"]["total_return"]))
        add(f"{tag}Turnover", percent(method["gross"]["turnover"], 2))
        counts = Counter(method["orders_selected"].values())
        add(f"{tag}KCounts", ", ".join(f"$K{{=}}{k}$: {counts[k]}$\\times$" for k in sorted(counts)))
        add(f"{tag}NSelections", len(method["orders_selected"]))
    daily = {
        n: pd.read_csv(ROOT / "results" / f"hmm_{n}_daily.csv", index_col=0)["gross_return"]
        for n in ("baseline", "blocked")
    }
    diff = daily["blocked"] - daily["baseline"]
    add("OneSeedT", number(diff.mean() / diff.std() * np.sqrt(len(diff)), 1))

    # multi-seed
    for suffix, label in (("base", "Base"), ("blocked", "Blk")):
        add(f"Seed{label}Sharpe", number(means[f"sharpe_{suffix}"], 3))
        add(f"Seed{label}MaxDD", percent(means[f"mdd_{suffix}"]))
        add(f"Seed{label}Turnover", percent(means[f"turn_{suffix}"], 2))
        add(f"Seed{label}Switches", number(means[f"k_switches_{suffix}"], 1))
        add(f"Seed{label}MeanK", number(means[f"k_mean_{suffix}"]))
        add(f"Seed{label}SharpeSD", number(per_seed[f"sharpe_{suffix}"].std(ddof=1), 3))
    add("SeedBaseSharpeMin", number(extremes["sharpe_base_min"]))
    add("SeedBaseSharpeMax", number(extremes["sharpe_base_max"]))
    add("DSharpeMin", signed(extremes["d_sharpe_min"]))
    add("DSharpeMax", signed(extremes["d_sharpe_max"]))
    add("DSharpeMean", signed(across["mean_d_sharpe"], 3))
    add("DSharpeLo", signed(across["ci95_mean"][0], 3))
    add("DSharpeHi", signed(across["ci95_mean"][1], 3))
    add("SeedsBetter", round(across["share_seeds_blocked_better"] * across["n_seeds"]))
    add("SeedsWorse", across["n_seeds"] - round(across["share_seeds_blocked_better"] * across["n_seeds"]))
    add("SeedsBetterShare", percent(across["share_seeds_blocked_better"], 0))
    add("TStat", number(across["paired_t"]["t"]))
    add("TP", number(across["paired_t"]["p"], 4))
    add("WilcoxonP", number(across["wilcoxon"]["p"], 4))
    add("RelGain", percent(across["mean_d_sharpe"] / means["sharpe_base"], 0))
    add("TurnoverCut", percent(1 - means["turn_blocked"] / means["turn_base"], 0))
    add("EnsBaseSharpe", number(boot["ensemble_sharpe_base"], 3))
    add("EnsBlkSharpe", number(boot["ensemble_sharpe_blocked"], 3))
    add("EnsDiff", signed(boot["point_diff"], 3))
    for block, word in ((10, "Ten"), (20, "Twenty"), (60, "Sixty")):
        entry = boot[f"block_{block}"]
        add(f"BootLo{word}", signed(entry["ci95"][0], 3))
        add(f"BootHi{word}", signed(entry["ci95"][1], 3))
        add(f"BootP{word}", number(entry["p_two_sided"], 3))
    for name, tag in (("2019_2022", "Early"), ("2023_2026", "Late")):
        entry = stats["by_period_across_seeds"][name]
        add(f"{tag}D", signed(entry["mean_d_sharpe"]))
        add(f"{tag}T", number(entry["paired_t"], 1))
        add(f"{tag}Share", percent(entry["share_seeds_blocked_better"], 0))
    rows = "%\n".join(
        f"{year} & {plain(v['baseline'])} & {plain(v['blocked'])} & "
        f"{signed(v['blocked'] - v['baseline'])} \\\\"
        for year, v in stats["by_year_ensemble_sharpe"].items()
    )
    lines.append("\\newcommand{\\ByYearRows}{%\n" + rows + "%\n}")
    (ROOT / "paper" / "numbers.tex").write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
